@url = http://10.110.133.212:8000
@json = Content-Type: application/json

###
get {{url}}

### 注册
post {{url}}/api/reguser
{{json}}

{
    "username":"user1",
    "password":"123456"
}

### 登录
post {{url}}/api/login
{{json}}

{
    "username": "admin",
    "password": "000000"
}

###
POST url HTTP/1.1
{{json}}
{
    "username":"admin",
    "password":"000000"
}